apiVersion: v1
kind: Pod
metadata:
  name: microcalculator
  labels:
    run: microcalculator
spec:
  containers:
  - image: kachio/updatedmicrocalculator
    name: nodewebapp
    ports:
    - containerPort: 5000
  dnsPolicy: ClusterFirst
  restartPolicy: Always