apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32100
  selector:
    app: mongodb
  type: NodePort

  